# Generated by Django 4.0.6 on 2022-07-23 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='reference',
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_intent_id',
            field=models.CharField(default='pi_1', max_length=120, unique=True),
            preserve_default=False,
        ),
    ]
