# Generated by Django 4.0.5 on 2022-06-13 18:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('special', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shoe_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp'])])),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.category')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('display', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'shoe',
            },
        ),
        migrations.CreateModel(
            name='ShoeSize',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'shoe_size',
            },
        ),
        migrations.CreateModel(
            name='ShoeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='shoe_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp'])])),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.shoe')),
            ],
            options={
                'db_table': 'shoe_image',
            },
        ),
        migrations.CreateModel(
            name='ShoeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.category')),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.shoe')),
            ],
            options={
                'verbose_name_plural': 'shoe categories',
                'db_table': 'shoe_category',
                'unique_together': {('category', 'shoe')},
            },
        ),
        migrations.CreateModel(
            name='AvailableShoeSize',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.shoe')),
                ('shoe_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.shoesize')),
            ],
            options={
                'verbose_name_plural': 'available shoe sizes',
                'db_table': 'available_shoe_size',
                'unique_together': {('shoe_size', 'shoe')},
            },
        ),
    ]
