# Generated by Django 4.0.6 on 2022-08-10 13:16

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('special', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shoe_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp'])])),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('display', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_restocked', models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 10, 14, 16, 11, 756229))),
            ],
            options={
                'db_table': 'shoe',
            },
        ),
        migrations.CreateModel(
            name='ShoeColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(default='default', max_length=50)),
                ('hex_code', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'db_table': 'shoe_color',
            },
        ),
        migrations.CreateModel(
            name='ShoeSize',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'shoe_size',
            },
        ),
        migrations.CreateModel(
            name='ShoeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('discount', models.DecimalField(decimal_places=1, default=Decimal('0.00'), max_digits=4)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.shoecolor')),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shoes.shoe')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.shoesize')),
            ],
            options={
                'db_table': 'shoe_variant',
            },
        ),
        migrations.CreateModel(
            name='ShoeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='shoe_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp'])])),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shoes.shoecolor')),
            ],
            options={
                'db_table': 'shoe_image',
            },
        ),
        migrations.CreateModel(
            name='ShoeFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('feature', models.CharField(max_length=255)),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='shoes.shoe')),
            ],
        ),
        migrations.CreateModel(
            name='ShoeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoes', to='shoes.category')),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='shoes.shoe')),
            ],
            options={
                'verbose_name_plural': 'shoe categories',
                'db_table': 'shoe_category',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('stars', models.PositiveSmallIntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')])),
                ('feedback', models.TextField(blank=True, max_length=255, null=True)),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.shoe')),
            ],
            options={
                'db_table': 'rating',
            },
        ),
    ]
