# Generated by Django 4.0.5 on 2022-06-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
