# Generated by Django 4.0.5 on 2022-06-14 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0002_alter_shoe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoeimage',
            name='shoe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shoes.shoe'),
        ),
    ]
