# Generated by Django 4.0.6 on 2022-08-10 15:27

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoeimage',
            name='medium',
            field=models.ImageField(default='a', upload_to='shoe_images/medium', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp'])]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoeimage',
            name='thumbnail',
            field=models.ImageField(default='qq', upload_to='shoe_images/thumbnail', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp'])]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoe',
            name='date_restocked',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 10, 16, 27, 37, 745990)),
        ),
    ]
