# Generated by Django 4.0.6 on 2022-08-18 08:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0003_shoeimage_medium_shoeimage_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoecolor',
            name='shoe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='shoes.shoe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoe',
            name='date_restocked',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 18, 9, 31, 24, 386847)),
        ),
        migrations.AlterField(
            model_name='shoevariant',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoes', to='shoes.shoecolor'),
        ),
        migrations.AlterField(
            model_name='shoevariant',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoes', to='shoes.shoesize'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('parent', 'name')},
        ),
    ]
