# Generated by Django 4.0.5 on 2022-06-14 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0003_alter_shoeimage_shoe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableshoesize',
            name='shoe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_shoe_sizes', to='shoes.shoe'),
        ),
        migrations.AlterField(
            model_name='shoecategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoes', to='shoes.category'),
        ),
        migrations.AlterField(
            model_name='shoecategory',
            name='shoe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='shoes.shoe'),
        ),
    ]
