# Generated by Django 4.0.5 on 2022-06-14 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0004_alter_availableshoesize_shoe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_id',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoes.category'),
        ),
        migrations.AlterField(
            model_name='shoesize',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
