# Generated by Django 4.0.6 on 2022-08-18 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0004_shoecolor_shoe_alter_shoe_date_restocked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='date_restocked',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 18, 9, 36, 15, 894247)),
        ),
        migrations.AlterUniqueTogether(
            name='shoecolor',
            unique_together={('name', 'shoe')},
        ),
    ]
