# Generated by Django 4.0.5 on 2022-06-15 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0007_alter_category_parent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
