# Generated by Django 4.0.5 on 2022-06-15 19:24

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0008_rename_parent_id_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoe',
            name='date_restocked',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 15, 20, 24, 25, 123043)),
        ),
    ]
