# Generated by Django 4.0.5 on 2022-06-16 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0009_shoe_date_added_shoe_date_restocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='price',
        ),
        migrations.AddField(
            model_name='availableshoesize',
            name='price',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoe',
            name='date_restocked',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 16, 19, 55, 30, 128455)),
        ),
    ]
