# Generated by Django 4.0.6 on 2022-07-20 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0010_remove_shoe_price_availableshoesize_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='date_restocked',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 20, 10, 17, 1, 817891)),
        ),
    ]
