# Generated by Django 4.0.6 on 2022-07-21 21:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0013_alter_cart_quantity_alter_shoe_date_restocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='shoe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_cart', to='shoes.availableshoesize'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='shoe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shoes.availableshoesize'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='date_restocked',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 21, 22, 0, 29, 602673)),
        ),
    ]
