# Generated by Django 4.0.6 on 2022-07-21 22:05

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shoes', '0015_cart_created_at_cart_modified_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='CartItem',
        ),
        migrations.AlterField(
            model_name='shoe',
            name='date_restocked',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 21, 23, 5, 36, 941086)),
        ),
    ]
