# Generated by Django 4.0.6 on 2022-07-22 12:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0016_rename_cart_cartitem_alter_shoe_date_restocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shoes.transaction'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='date_restocked',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 22, 13, 17, 16, 624344)),
        ),
    ]
