# Generated by Django 4.0.6 on 2022-07-23 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0018_remove_transaction_user_alter_shoe_date_restocked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='date_restocked',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 23, 18, 41, 36, 552813)),
        ),
    ]
