# Generated by Django 4.0.6 on 2022-07-23 23:49

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0019_alter_shoe_date_restocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableshoesize',
            name='discount',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.00'), max_digits=4),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='date_restocked',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 24, 0, 49, 3, 215387)),
        ),
    ]
