# Generated by Django 4.0.6 on 2022-07-26 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0020_availableshoesize_discount_alter_shoe_date_restocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='feedback',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='date_restocked',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 26, 11, 9, 29, 650507)),
        ),
    ]
